### ISSUE TITLE
SAR: Add Integration tile for elastic-serverless-forwarder in the Integrations UI

### ISSUE THREAD

**Issue by ravikesarwani** [elastic/elastic-serverless-forwarder#100]
Improve the discovery of elastic-serverless-forwarder functionality for the users. Currently the users (both internal and external) have hard time finding the serverless data ingestion method. Adding a tile in the Integrations UI creates visibility and provides a way for the users to discover the functionality more easily.

- [ ] Clicking the tile will forward the users to “https://github.com/elastic/elastic-serverless-forwarder/blob/main/docs/README-AWS.md”.  We already have this kind of mechanism being utilized for other things like Language client.

- [ ] The tile should be visible in the “AWS” and “Custom” section.

- [ ] Details of the tile:

- Use the AWS Serverless Application Repository icon. 

<img width="157" alt="Screen Shot 2022-03-28 at 9 40 06 AM" src="https://user-images.githubusercontent.com/64450378/160411066-1c4b476f-1b5d-443b-b217-1c81c770f317.png">

- Bold text says “AWS Serverless Application Repository”.

- Detailed text says “Collect logs using AWS Lambda application available in AWS Serverless Application Repository.”

cc: @aspacca

**Comment by ravikesarwani** [comment]
@amena-siddiqi Let me know if you have any feedback on this?

**Comment by sayden** [comment]
I have started some work here https://github.com/elastic/kibana/pull/130085

**Comment by aspacca** [comment]
https://github.com/elastic/kibana/pull/130085 was merged

**Comment by aspacca** [comment]
@ravikesarwani can we close this issue?

**Comment by ravikesarwani** [comment]
@aspacca Is it available in production? I don't see it. Quick questions:
- Is there a kibana version dependency on this? If yes, what is it?
- Is it promoted to production?

**Comment by aspacca** [comment]
@ravikesarwani it will land in 8.3

**Comment by ravikesarwani** [comment]
Is there a technical reason that its tagged only for 8.3+?
Can we make it available for 7.17+ so that many users have visibility of it and see it in Kibana.
Making it for 8.3+ will miss out seeing this for most users that can use this functionality.

**Comment by aspacca** [comment]
@ravikesarwani the integrations tile was backported to 8.2 and 7.17

closing this
