### ISSUE TITLE
Unable to parse event from cloud watch-log

### ISSUE THREAD

**Issue by jmilushe** [elastic/elastic-serverless-forwarder#108]
Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 0.27.0
- Setup trigger for cloud watch logs created by RDS database, i.e. - logStream:group=/aws/rds/cluster/database-1/error)
- Add an instance to the database, which will generate log entries

The lambda function executes and logs an error:
[ERROR] TriggerTypeException: Not supported trigger
Traceback (most recent call last):
  File "/var/task/main_aws.py", line 17, in handler
    return lambda_handler(lambda_event, lambda_context)
  File "/var/task/elasticapm/contrib/serverless/aws.py", line 116, in decorated
    self.response = func(*args, **kwds)
  File "/var/task/handlers/aws/utils.py", line 109, in wrapper
    raise e
  File "/var/task/handlers/aws/utils.py", line 99, in wrapper
    return func(lambda_event, lambda_context)
  File "/var/task/handlers/aws/handler.py", line 61, in lambda_handler
    raise TriggerTypeException(e)

[lambda_log.csv](https://github.com/elastic/elastic-serverless-forwarder/files/8525879/lambda_log.csv)
[log-events-viewer-result-showing-event.csv](https://github.com/elastic/elastic-serverless-forwarder/files/8525881/log-events-viewer-result-showing-event.csv)

**Comment by aspacca** [comment]
@jmilushe thanks for reporting the issue.
could you add the environment variable `LOG_LEVEL=DEBUG` to the lambda and share the debug log?
please, amend any sensible information before sharing.

and if you can share the content of the `S3_CONFIG_FILE` (always with sensible information amended).

what version of the lambda are you running?

**Comment by aspacca** [comment]
hello @jmilushe , I've identified the problem, I've fixed in #107 
once it will be merged I will release a new version
