### ISSUE TITLE
Amazon EKS Control Plane Logging 

### ISSUE THREAD

**Issue by DefSecSentinel** [elastic/elastic-serverless-forwarder#109]
**Describe the enhancement:**
EKS has different log streams in the same log group: the forwarder doesn't handle this at the moment. Add support for this and implement the forwarding capability for EKS audit logs. 

https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html

**Describe a specific use case for the enhancement or feature:**
There is a VERY strong need to be able to use this serverless forwarder to forward EKS audit logs to the Elastic stack utilizing the Kubernetes Audit Log integration pipeline when the data gets ingested to properly parse and utilize this data.

**Comment by ravikesarwani** [comment]
cc: @elastic/obs-cloudnative-monitoring Miguel, Andreas, Christos let us know if you folks have any additional comments or thoughts on this.

**Comment by aspacca** [comment]
@ravikesarwani everything ok from side

**Comment by gizas** [comment]
Looks good @ravikesarwani ! One note as arn is unique do you need the rest of info? (I mean are already implied in the arn) Maybe you can use only arn
