### ISSUE TITLE
CloudWatch parse always raise UnicodeDecodeError

### ISSUE THREAD

**Issue by riccardofuziercayla** [elastic/elastic-serverless-forwarder#111]
Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 0.28.0
- Steps to Reproduce: every run triggered by cloudwatch logs

Whenever the Lambda function is triggered by a CloudWatch logs it raise an UnicodeDecodeError.

[log-events-viewer-result.csv](https://github.com/elastic/elastic-serverless-forwarder/files/8566092/log-events-viewer-result.csv)

**Comment by aspacca** [comment]
hello @riccardofuziercayla 

CloudWatch Logs input was indeed broken in 0.28.0
It was fixed in [lambda-v0.28.4](https://github.com/elastic/elastic-serverless-forwarder/releases/tag/lambda-v0.28.4)

You should have got another error anyway, so please try the newest version and let me know if you still have `UnicodeDecodeError`

**Comment by zenon102** [comment]
hi @aspacca 
I have exactly the same problem using both version 2.8.4 and 2.9.0. I have removed almost everything from my lambda test function, it only generates the standard plain text AWS log with start/end and execution duration info. 
Can you verify if the problem has actually been fixed?

[config.yaml.txt](https://github.com/elastic/elastic-serverless-forwarder/files/8602505/config.yaml.txt)
[test_lambda.csv](https://github.com/elastic/elastic-serverless-forwarder/files/8602502/test_lambda.csv)
[esf_lambda.csv](https://github.com/elastic/elastic-serverless-forwarder/files/8602503/esf_lambda.csv)

**Comment by aspacca** [comment]
hello @zenon102

I was able to identify the bug thanks the the debug log 👍 

It will be fixed in #113
