### ISSUE TITLE
Unescape message before sending data to Elastic and treat it as JSON and not as plain text

### ISSUE THREAD

**Issue by expertalex** [elastic/elastic-serverless-forwarder#153]
**Describe the enhancement:**
Hi

We are using Lambda to get Records from Kinesis and send it to Elastic

Giving the following Input:
![image](https://user-images.githubusercontent.com/10635008/185619666-9d5927ea-fc01-4da3-ba46-05c9d966b9c9.png)

The output data looks is treated as an escaped string and placed inside the message:
![image](https://user-images.githubusercontent.com/10635008/185398380-2ed3e6b6-c2c1-4648-81b6-e9f36b00e1f9.png)

How can we get all the messages as JSON inside Elastic customizing the S3_CONFIG_FILE YAML file?

Current config file:
`inputs:
  - type: "s3-sqs"
    id: "***"
    expand_event_list_from_field: "Records"
    outputs:
      - type: "elasticsearch"
        args:
          cloud_id: "***"
          api_key: "***"
          es_index_or_datastream_name: "aws-alb-logs"
          batch_max_actions: 500
          batch_max_bytes: 10485760
  - type: "kinesis-data-stream"
    id: "***"
    expand_event_list_from_field: "Records"
    outputs:
      - type: "elasticsearch"
        args:
          cloud_id: "***"
          api_key: "***"
          es_index_or_datastream_name: "atc-log-test-2022"
          batch_max_actions: 500
          batch_max_bytes: 10485760
`

**Describe a specific use case for the enhancement or feature:**

**Comment by aspacca** [comment]
hello @expertalex 

If I got it right your are have CloudWatch Logs with a Kinesis Data Stream as destination of a subscription filter.
And you would like to send the original entries of the CloudWatch Logs as separated events to elasticsearch, is it correct?

You should set `expand_event_list_from_field: "logEvents"`:
```
type: "kinesis-data-stream"
id: "***"
expand_event_list_from_field: "logEvents"
outputs:
    type: "elasticsearch"
    args:
        cloud_id: ""
        api_key: ""
        es_index_or_datastream_name: "atc-log-test-2022"
        batch_max_actions: 500
        batch_max_bytes: 10485760
``

**Comment by expertalex** [comment]
hello @aspacca thank you for the quick response. 

I changed the expand_event_list_from_field: "logEvents" in kinesis-data-stream
![image](https://user-images.githubusercontent.com/10635008/185406786-b9b47618-a6e3-4063-831c-7a37ffb05ec5.png)
and the output is still the same:
![image](https://user-images.githubusercontent.com/10635008/185406618-40240044-8d17-4835-9cb3-f778ac463bbe.png)

**Comment by aspacca** [comment]
@expertalex what version of the forwarder are you using?

if you set a breakpoint at https://github.com/elastic/elastic-serverless-forwarder/blob/lambda-v1.3.0/handlers/aws/handler.py#L217, what's the value of `expand_event_list_from_field`?

**Comment by expertalex** [comment]
We are using version 0.27 
Our input looks like this: 
Inside Records, we want to go to kinesis and inside it to Data.
![image](https://user-images.githubusercontent.com/10635008/185618869-6b95a689-8e46-46b6-adb9-8b0079eb65de.png)
I am not sure if we can relate to the example provided in the wiki
![image](https://user-images.githubusercontent.com/10635008/185619137-36cf00aa-4061-4d03-8e6b-9b99e6d8ccd2.png)

**Comment by aspacca** [comment]
@expertalex you should bump the version to the latest. v0.27 was still a beta release.
specifically the feature you are looking for was added in v1.1.0


the example in the wiki is related to the content of the payload of the input once it's parsed, not to the original payload of the trigger of the lambda. Maybe we could clarify better.

kinesis trigger payload is in the format `{"Records":[{"kinesis":{"data":base64encode(%AN INPUT PAYLOAD%) }]}`

You don't need to handle the extraction from `Records`, the forwarder will do for you when dealing with a kinesis input, and process every `Records.[].kinesis.data`, also taking care of the base64 decoding.

In the end what you have in `%AN INPUT PAYLOAD%` is `{"logEvents":[{"message":...},{"message":...}]}` and what you want to do is sent to  Elasticsearch every `{"message":...}` as single events.

For this you have to extract and events list form the field `logEvents`

**Comment by essodjolo** [comment]
Thanks a lot @aspacca for providing these helpful details. I currently have a similar situation with one of my users. I also suggested they use `expand_event_list_from_field: "logEvents"` but it didn't work for them and I was wondering why.
I'm checking the version of their forwarder now and have asked them to upgrade to the latest.
I'll comment here about the outcome.

**Comment by aspacca** [comment]
@expertalex . could you please confirm that bumping the forwarder to latest version solved the issue? thanks :)

**Comment by expertalex** [comment]
Now it is working! Thank you very much @aspacca!!!

**Comment by essodjolo** [comment]
Same for my user. Thanks @aspacca.
