### ISSUE TITLE
✨ Implement an option for disable SSL Certificate Verify

### ISSUE THREAD

**Issue by Ben00it** [elastic/elastic-serverless-forwarder#164]
Hello, 

We are trying to deploy it without SSL signed on ElasticSearch side, and it doesn't seem to work without SSL Signed.

Please find below the error we have : 

```JSON
{
    "@timestamp": "2022-09-29T11:54:37.848Z",
    "log.level": "warning",
    "message": "elasticsearch shipper",
    "_id": "f5d4f08ae9-000000000000",
    "ecs": {
        "version": "1.6.0"
    },
    "error": "ConnectionError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)) caused by: SSLError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129))",
    "log": {
        "logger": "root",
        "origin": {
            "file": {
                "line": 167,
                "name": "es.py"
            },
            "function": "_handle_outcome"
        },
        "original": "elasticsearch shipper"
    },
    "process": {
        "name": "MainProcess",
        "pid": 8,
        "thread": {
            "id": 140115916543808,
            "name": "MainThread"
        }
    }
}
```

Would it be possible to add an option into the `config.yaml` file to handle no certificate verification (We use auto-signed certificate).

Many thanks for the :sparkles: ^^ 

Hints Reference : 
https://github.com/elastic/elastic-serverless-forwarder/blob/8fd2d8af994bf91536f04ff3ccf24335b759e3ee/shippers/es.py#L108

**Comment by aspacca** [comment]
@Ben00it do you use a self-hosted ES cluster?

The option to expose should be `ca_certs` (https://elasticsearch-py.readthedocs.io/en/v7.17.6/transports.html#urllib3httpconnection), but unluckily there is no easy way to provide the proper value on a Lambda deployed from SAR: since it requires to add the cert files to a path accessible from the lambda

**Comment by aspacca** [comment]
The best would be if you are able to generate public certs with letsencrypt or similar

**Comment by JeromeSola** [comment]
Hello @aspacca,
Thanks for the quick response,
What about the "verify_certs" option ? We were using functionbeat before and it was possible to use  the option "verification_mode=none" (https://www.elastic.co/guide/en/beats/functionbeat/current/configuration-ssl.html#client-verification-mode).
It would help us a lot to have this option in this repository.

Thanks for your help

**Comment by aspacca** [comment]
@JeromeSola `verify_certs` is prone to open a secure vulnerability I would prefer to consider all the other available options before making a call on that

please, don't consider my question a judgement on your security practice, but what are the limit that would prevents youto generate a valid cert from a certificate authority? :)

Have you looked at https://aws.amazon.com/certificate-manager/? (assuming your cluster is on the aws cloud)

**Comment by JeromeSola** [comment]
@aspacca i see your point.

However i think it is required to know the full context to admit if their is a security breach or not. Our cluster is well hosted in AWS in a full private network etc...
Moreover it is difficult on our buisiness context to have access to some ressources while it is easy for us to make this simple change on the config file and our network segmentation does not expose critical stuff.

That's why I thought it was a good thing to just add options to your tool then it is client security concern to use or not use the option...

Thanks anyway

**Comment by aspacca** [comment]
@JeromeSola as I said I'm not discussing your specific use case and infra scenario. but the option to have somehow a lower security standard :)

If not for the complexity of relying on `ca_certs` in a Lambda context it would be the primary and immediate choice to add support for self-signed certificates.

I've brought the topic to discussion internally to the team and I will keep you posted

**Comment by aspacca** [comment]
@JeromeSola please, take a look at #173

**Comment by aspacca** [comment]
@Ben00it please, take a look at #173

**Comment by JeromeSola** [comment]
Nice ! 
Waiting for the feature to be merged to migrate from function beat to elastic-serverless-forwarder :heart_eyes:

**Comment by Ben00it** [comment]
Hello, Oh a good news, that's great. 

We will migrate that asap once merged and we will let you know. 

Thank you @aspacca

**Comment by JeromeSola** [comment]
Hello @aspacca we were looking to deploy the new version, unfortunatly we use [AWS repository](https://serverlessrepo.aws.amazon.com/applications/eu-central-1/267093732750/elastic-serverless-forwarder) to deploy the tool and it seems to still be the old version of the tool. 

What is your process to push a new version to AWS repository? Can we expect the new version to be pushed soon ?
Thanks :)

**Comment by aspacca** [comment]
@JeromeSola pushed the new version yesterday after a little while from your messsage :)
