### ISSUE TITLE
Lambda times out trying to access the continuing SQS queue

### ISSUE THREAD

**Issue by zmoog** [elastic/elastic-serverless-forwarder#197]
- Version: 1.5.0

Steps to Reproduce:

1. Install the ESF
2. Create a `cloudwatch-logs` input
3. Attach the ESF's lambda function to a VPC
4. Add the environment variable `LOG_LEVEL=DEBUG`
5. Set a 10s timeout on the lambda to make it send all in-flight events to the SQS continuing queue.

In this scenario, after processing the first event, the lambda function will try to send all in-flight messages to the continuing SQS queue and will get stuck at this step:

```json
{
    "@timestamp": "2022-12-28T14:01:44.308Z",
    "log.level": "debug",
    "message": "Starting new HTTPS connection (1): us-west-2.queue.amazonaws.com:443",
    "ecs": {
        "version": "1.6.0"
    },
    "log": {
        "logger": "urllib3.connectionpool",
        "origin": {
            "file": {
                "line": 1003,
                "name": "connectionpool.py"
            },
            "function": "_new_conn"
        },
        "original": "Starting new HTTPS connection (1): us-west-2.queue.amazonaws.com:443"
    },
    "process": {
        "name": "MainProcess",
        "pid": 8,
        "thread": {
            "id": 139626632742720,
            "name": "MainThread"
        }
    }
}
```

**Comment by zmoog** [comment]
It looks like this issue is similar to #192

**Comment by zmoog** [comment]
To work correctly, the user must allow the Lambda function to access SQS by creating—for example—an Amazon VPC endpoint for Amazon SQS.

**Comment by zmoog** [comment]
We should probably add a section to describe how to configure ESF for VPC.

**Comment by aspacca** [comment]
> We should add a section to describe how to configure ESF for VPC.

https://github.com/elastic/observability-docs/pull/2473
