### ISSUE TITLE
Support enricher/processor on events

### ISSUE THREAD

**Issue by Holi0317** [elastic/elastic-serverless-forwarder#235]
**Describe the enhancement:** Add configurable enricher/processor for events

**Describe a specific use case for the enhancement or feature:**

We are considering migrate away from functionbeat to serverless forwarder. But serverless forwarder doesn't seem to have the ability to do pre-processing before sending the logs to elastic. In particular, we want to use the [`add_fields`] processor from functionbeat to hard-code some field in config.

The specific usecase for us is we are producing lambda logs to cloudwatch. Then we ship the logs from cloudfront to elastic. Problem here is some lambda are not producing logs in ECS format and we need to populate some ECS fields about the lambda. For example, `service.name` and `service.role` for us to search the log easily.

In the current setup with functionbeat, we use [`dissect`] on the log group name to determine lambda name and the service properties. When we move to serverless forwarder, we will manage the deployment with terraform. So we can move the service property parsing logic to terraform and generate a set of fields that need to be included in every ECS event. But still, we need a way to configure serverless forwarder to include the fields.

TBH I am not sure if serverless forwarder really need this feature. This sounds like opening the gate for cramping too much logic into this module and make the project harder to maintain. I'm ok with using [ingestion pipeline] if serverless forwarder decide not to add the feature.

[`add_fields`]: https://www.elastic.co/guide/en/beats/functionbeat/current/add-fields.html
[`dissect`]: https://www.elastic.co/guide/en/beats/functionbeat/current/dissect.html
[ingestion pipeline]: https://www.elastic.co/guide/en/elasticsearch/reference/master/ingest.html

**Comment by pushred** [comment]
Found this thread where [the advice](https://discuss.elastic.co/t/elastic-forwarder-not-decoding-json/319330/5) was to use ingest pipelines, not sure if thinking has changed on that since November 2022.

**Comment by aspacca** [comment]
> In the current setup with functionbeat, we use [`dissect`](https://www.elastic.co/guide/en/beats/functionbeat/current/dissect.html) on the log group name to determine lambda name and the service properties. When we move to serverless forwarder, we will manage the deployment with terraform. So we can move the service property parsing logic to terraform and generate a set of fields that need to be included in every ECS event. But still, we need a way to configure serverless forwarder to include the fields.

hello @Holi0317 , we don't plan to add any enrichment processors (but for the existing possibility to add values to the `tags` field) to the Forwarder.

Different is the use case where we need to provide ways to build the proper message to forwarder based on existing content of the source: for this we support [json parsing](https://www.elastic.co/guide/en/observability/current/aws-elastic-serverless-forwarder-configuration.html#aws-serverless-json-content), [`expand_event_list_from_field`](https://www.elastic.co/guide/en/observability/current/aws-elastic-serverless-forwarder-configuration.html#expanding-events-from-json-object-lists), [`multiline`](https://www.elastic.co/guide/en/observability/current/aws-elastic-serverless-forwarder-configuration.html#aws-serverless-manage-multiline-messages) and we will support  something like [`add_root_fields_to_event_list_extracted_from_field`](https://github.com/elastic/elastic-serverless-forwarder/issues/162)

All the rest of the processing/enrichment, compared to functionbeat, should be moved to an ingest pipeline

For your specific case, you can probably rely on `tags` in the ingest pipeline

**Comment by Holi0317** [comment]
@aspacca Sounds reasonable. I'll try out tags and ingestion pipeline on elastic side.

Closing this issue as not planned.
