### ISSUE TITLE
ThrottlingExceptions while processing data from cloudwatch input

### ISSUE THREAD

**Issue by zmoog** [elastic/elastic-serverless-forwarder#264]
Note: this is a placeholder issue; I will add more details soon.

***

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version:
- Steps to Reproduce:

**Comment by davidchoi-aus** [comment]
@zmoog I have a customer running into the issue.

Version: ESF v1.7.1
Logs: 
`{"@timestamp":"2023-02-22T19:27:08.070Z","log.level":"error","message":"exception raised","ecs":{"version":"1.6.0"},"error":{"message":"An error occurred (ThrottlingException) when calling the DescribeLogStreams operation (reached max retries: 4): Rate exceeded","stack_trace":" File \"/var/task/handlers/aws/[utils.py](https://utils.py/)\", line 83, in wrapper`

Search Config:

https://elastic.slack.com/archives/C02H9A97ATX/p1678235567750409

**Comment by zmoog** [comment]
Hey, @davidchoi-aus, thanks for reporting this issue!

@aspacca prepared a fix, and we will ship it with a new release as soon as it is ready (targeting 1.7.2).

**Comment by zmoog** [comment]
@davidchoi-aus, the ESF version 1.7.2 is available with a fix to this ThrottlingExceptions issue. 

Let us know if it works in your case.
