### ISSUE TITLE
[Lambda] Elastic serverless forwarder producing errors with the Macro application during the upgrade to 1.8.0

### ISSUE THREAD

**Issue by DK-Elastician** [elastic/elastic-serverless-forwarder#322]
Hello Team, IHAC where they are experiencing errors when upgrading to version 1.8.0. The Macro Application is receiving the error.  (See Attached screenshot_

Reproduction:

1. Open AWS Console -> Lambda -> Publish a new entity or Navigate to the Elasticservless repo AWS service 
2. Search up ESF & choose the updated version
3. Defining the environment setting (KMS, security groups, lambda subnets, etc)
4. Once deploy, we see the errors within the upgrade activity

How can we resolve these errors with the ESF?

As a future walk around, would be it possible to prevent the older patches getting deleted before the new version is deployed?

![Screenshot 2023-04-05 at 8 43 39 AM](https://user-images.githubusercontent.com/109980858/230149502-1bd9e4df-e2b2-48ac-813b-e6a274d025e4.png)

![Screenshot 2023-04-05 at 8 44 26 AM](https://user-images.githubusercontent.com/109980858/230149515-bb25faf8-b5dd-44a9-81e2-c5fbd1a24e0e.png)

**Comment by girodav** [comment]
Hi @DK-Elastician, updates should go through without problems, even if ESF is deployed through SAR. There is currently a limitation that prevents multiple instances of ESF to be deployed through SAR in the same region. However, updates should not be affected by this as far as the application name does not change. 

<img width="850" alt="Screenshot 2023-04-13 at 12 13 14" src="https://user-images.githubusercontent.com/1390902/231741722-7b404f1b-f0db-4000-b08e-1608f9365a2f.png">

The above note is taken from our public documentation https://www.elastic.co/guide/en/observability/master/aws-deploy-elastic-serverless-forwarder.html#aws-serverless-forwarder-deploy-console

Could you confirm that the application name hasn't been changed? 

It would also be beneficial to have the actual error from the MacroElasticServerlessForwarder stack, not only the main one. It would help us understand what exactly went wrong with its creation.

**Comment by DK-Elastician** [comment]
Hello @girodav, 
I believe in order to upgrade the ESF, we had to go through a final step with saving the configuration and we named the deployment. I would have to double check on that, but I can take at their AWS account and try to obtain the second error.

**Comment by girodav** [comment]
> Also, if the rename was the issue, would the solution be simply renaming the upgrade to the original Application name, correct?

Yes, if the Application Name stays the same, the underlying Cloudformation stack gets updated accordingly, instead of spinning up a new Cloudformation stack

**Comment by DK-Elastician** [comment]
Hello @girodav,

We believe the cause of the error was related to a change in the application name

**Comment by aspacca** [comment]
> We believe the cause of the error was related to a change in the application name

@DK-Elastician is it confirmed? can we close the issue? thanks
