### ISSUE TITLE
Tagging for artifacts created by deploying the SAR

### ISSUE THREAD

**Issue by PeterPaulH** [elastic/elastic-serverless-forwarder#384]
**Describe the enhancement:**
We would like to be able to specify some tags that would be set when deploying the SAR. We would like to be able to specify these tags for each artifact that is created.

**Describe a specific use case for the enhancement or feature:**
We have very strict tagging conventions and need to be able to set the tags according to these conventions.
Right now we have to set the tags in a "after deploy script", but that will break the terraform setup of the SAR.

**Comment by aspacca** [comment]
see the same comment as for #368 
I'd rather add this feature to [direct deployment](https://www.elastic.co/guide/en/esf/master/aws-deploy-elastic-serverless-forwarder.html#aws-serverless-forwarder-direct-deploy)

**Comment by PeterPaulH** [comment]
Ok,
leave this ticket as reference
