### ISSUE TITLE
[Docs] Review and improve guidance around AWS costs

### ISSUE THREAD

**Issue by ollyhowell** [elastic/elastic-serverless-forwarder#444]
**Describe the enhancement:**
We've had feedback from one customer that the documentation could have highlighted potential AWS-related costs more clearly. This was initially understood to be a functional issue that has since been rectified but it makes sense to review the current guidance (e.g. there is a troubleshooting topic that could be mirrored as a high profile warning on index page) with a view to improving and making more prominent, especially for older versions.

Suggested contacts:
Tech lead: @tommyers-elastic 
Product lead: @vinaychandrasekhar
Writer: @dedemorton 
Escalations: Basile Martin

This might be duplicate issue but waiting on confirmation and we can always link and dedupe...

**Comment by tommyers-elastic** [comment]
our friends in Cloud Security Posture Management include the following banner at integration install-time to warn customers of the additional charges. I think it's better than what we have today in o11y. I don't think it's a complete solution, but could be a good start - especially if we include a link to a docs page with more detail.

<img width="809" alt="Screenshot 2023-07-31 at 16 28 53" src="https://github.com/elastic/elastic-serverless-forwarder/assets/106530686/63c10d74-a3b9-44f6-a0fe-2f30006d693c">

**Comment by dedemorton** [comment]
This looks straightforward from a docs perspective, so I'll add it to my pile for this week.
