### ISSUE TITLE
Where is the IAM Role created?

### ISSUE THREAD

**Issue by jstarego16** [elastic/elastic-serverless-forwarder#461]
I am looking to customize the name of IAM Role create for the lambda function in order to comply with my company's Governance rules.  I cannot find where the code actually creates the role in order for me to alter it with the template to conform to my company's rules.  Can anyone point that out to me?

**Comment by tommyers-elastic** [comment]
https://github.com/elastic/elastic-serverless-forwarder/blob/main/.internal/aws/cloudformation/macro.yaml#L94

**Comment by tommyers-elastic** [comment]
Hey @jstarego16, the role is automatically generated by SAM, as per the docs [here](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources-function.html#sam-specification-generated-resources-function-not-role).

In our macro (which is used during the deployment of ESF), we do define a custom IAM policy which is attached to the lambda's execution role. That code is [here](https://github.com/elastic/elastic-serverless-forwarder/blob/f5c792792eb4df9dfddd582c0baa4b848ef22a77/.internal/aws/cloudformation/macro.yaml#L94). 

You could override the default execution role by adding a `Role` name [here](https://github.com/elastic/elastic-serverless-forwarder/blob/f5c792792eb4df9dfddd582c0baa4b848ef22a77/.internal/aws/cloudformation/application.yaml#L62) (or adding it into the macro function), but you would of course have to create the role by hand before deploying ESF.

**Comment by girodav** [comment]
Hey @jstarego16, thank you very much for bringing this up. We are working on allowing custom roles through the deployment script in https://github.com/elastic/elastic-serverless-forwarder/pull/399

**Comment by tommyers-elastic** [comment]
the above mentioned PR is now merged

**Comment by jstarego16** [comment]
Thanks for the info fellas.  I'm anxious to try this out.
