### ISSUE TITLE
VPC - anyone gotten this to work in a VPC?

### ISSUE THREAD

**Issue by jstarego16** [elastic/elastic-serverless-forwarder#486]
v1.9.0
Trying to get this to work with the lambda function in a VPC.
Created an S3 endpoint, this works.
However, the code tries to reach HTTPS ec2.us-east-1.amazonaws.com:443 with the DescribeRegions action and it times out.  Do I need an endpoint to ec2 service?  I have an internet gateway set up with routing out and security group permissions.  What am I missing?

**Comment by jstarego16** [comment]
<img width="1098" alt="Screen Shot 2023-09-13 at 1 10 08 PM" src="https://github.com/elastic/elastic-serverless-forwarder/assets/28869302/0bac7af9-c0f9-4128-b333-799523c8e23d">

This is my route table ^^^^ attached to the subnet in the VPC where the lambda function is running

**Comment by aspacca** [comment]
@jstarego16 

yes, we forgot to update the documentation to mention the fact that you need a vpc endpoint also for ec2, if you have cloudwatch logs input, after we removed the calls to `logs:DescribeLogGroups` and `logs:DescribeLogStreams`. sorry, we'll fix as soon as possible.

it is indeed unexpected that the ec2 instances in the same vpc of the lambda is able to reach the https endpoint without an vpc one for the service, but maybe this is related to the fact that the service is the same ("ec2 over ec2")

**Comment by katrin-freihofner** [comment]
https://github.com/elastic/elastic-serverless-forwarder/issues/488

**Comment by aspacca** [comment]
hello @jstarego16 We've updated the documentation about networking and VPC: https://www.elastic.co/guide/en/esf/master/aws-deploy-elastic-serverless-forwarder.html#_network
