### ISSUE TITLE
Terraform definition

### ISSUE THREAD

**Issue by aspacca** [elastic/elastic-serverless-forwarder#647]
**Describe the enhancement:**

We want to make available to users a terraform definition for deploying ESF without relying on SAR.
Feature parity with the direct deployment script (https://github.com/elastic/elastic-serverless-forwarder/blob/main/publish_lambda.sh) but with more focus on IaC common practices and solutions

**Describe a specific use case for the enhancement or feature:**
The direct deployment script does not fit IaC common practices and solutions 100%. And deployment through SAR is limited in the context of features we can expose because of the UI.

**Comment by ltflb-bgdi** [comment]
@aspacca This would be very useful, since the current implementation using the SAR has limited functionality and we don't want to use the script in terraform. Do you have an idea when we can expect this feature?

**Comment by audioboxer217** [comment]
I have a client that has been asking for this for a while. It would be very helpful as they have also had issues using the SAR via Terraform.
