### ISSUE TITLE
Investigate ingestion of files with same IDs

### ISSUE THREAD

**Issue by gizas** [elastic/elastic-serverless-forwarder#677]
Currently in ESF  as per [PR](https://github.com/elastic/elastic-serverless-forwarder/issues/212), we generate _id within Elastic Serverless Forwarder. For example for s3 logs retrieval, the generated id is based on {bucket_arn}, {object_key} and timestamp (see [info](https://github.com/girodav/elastic-serverless-forwarder/blob/3b04b9045b8118baaca3fa8e6c7d4c1a41dcb23a/handlers/aws/utils.py#L444-L447)). 

There are cases reported where events can have same _ids, thus this creates one event to be ingested in ES and the second to go to replay queue and eventually to dead letter queue due to failure of ingestion.

We should investigate a graceful way to identify that this events are duplicates and not pollute replay queues with unnecessary messages. 

## Related links:

- https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/using-messagededuplicationid-property.html
- https://aws.amazon.com/blogs/storage/manage-event-ordering-and-duplicate-events-with-amazon-s3-event-notifications/

**Comment by constanca-m** [comment]
I was doing some runs (you can see the details in this https://github.com/elastic/elastic-serverless-forwarder/pull/725#issuecomment-2149596032). Look at how much the error rate increases:

![image](https://github.com/elastic/elastic-serverless-forwarder/assets/113898685/a49d730c-52c1-4f94-8a4b-49aa696a72f4)

I went to look and the exception that was in the cloudwatch logs was:

```
version conflict, document already exists (current version [1])
```
