### ISSUE TITLE
SAR: Research and document auto discovery of AWS service logs based on events

### ISSUE THREAD

**Issue by ravikesarwani** [elastic/elastic-serverless-forwarder#83]
Currently when users use elastic-serverless-forwarder to send AWS services logs to Elastic they have to understand our data stream naming convention, find out what the default data stream name is (that's setup by the integration) and then specify the name as a config value to get the data routed correctly to Elastic and utilize the OOTB assets (index template, pipeline, dashboards etc.). We currently have auto routing but that's based on S3 object naming convention and hence works only for Amazon S3 input. This issue is to research using the events data itself to identify the AWS service log for all the OOTB supported AWS services logs, so that the method works for all supported inputs (including Kinesis data stream, SQS, CloudWatch logs).

For other complex use cases users can continue to specify the config value.

This issue is to research and document the findings for auto discovery of AWS service logs based on events data.
This issue scope would be to focus right now on the AWS service logs that we have supported integrations for.
These are the current AWS log integrations we have (based on index template we install). 
![image](https://user-images.githubusercontent.com/64450378/154530173-e98ca2ff-625f-44be-b8a3-ed6e479bae3d.png)

**Comment by endorama** [comment]
Is this like https://github.com/elastic/beats/issues/19200 but for logs?

**Comment by andresrc** [comment]
We will try to look for a way to do the routing outside the forwarder, so that it can be reused for other ingestion mechanism.
