### ISSUE TITLE
As part of forwarder deployment create the S3_CONFIG_FILE environment variable to simplify configuration by user and scripts

### ISSUE THREAD

**Issue by ravikesarwani** [elastic/elastic-serverless-forwarder#85]
Currently we expect the users to add and set the S3_CONFIG_FILE environment variable.

This enhancement is to create the environment variable as part of the deployment:
Add the environment variable "S3_CONFIG_FILE" with value something like "s3://bucket-name-chageme/config-file-changeme"

This helps users not to have to remember the environment variable name, see the format of the value and more easily set the S3 URI value to the config file.

**Comment by ravikesarwani** [comment]
cc: @Udayel

**Comment by aspacca** [comment]
@ravikesarwani using something like `s3://bucket-name-chageme/config-file-changeme` could have security implications. either we reserve a bucket name (that's unique across whole AWS) or we might let the lambda inadvertently try to access a bucket that's not owned by the users
